/**
 * This package contains the necessary classes to facilitate output from a
 * simulation model run to a database.<br>
 * <br>
 * The Factory classes provide the ability to generate outputters of various
 * types. Currently there exist three main types of outputters. The
 * BasicOutputter is an outputter that is to be associated with a completely
 * sequential operation of a simulation model. That is it operates completely
 * within the programs main thread of execution. The SingleOutputter creates is
 * an outputter which complete operates within a single thread that has been
 * spawned from the main thread of execution. Finally, there is the
 * ParallelOutputter, which both operates in its own thread of execution and can
 * spawn multiple threads to handle its output load.<br>
 * <br>
 * Working in conjunction with outputters are two other types of classes:
 * OutputProcessors and OutputQueues of which there is a specific type for each
 * type of Outputter.<br>
 * <br>
 * OutputQueues provide a means of listening to and storing OutputEvents
 * generated by IOutputProviders. These OutputQueues then feed the output into
 * an associated OutputProcessor which then formats the output and inserts it
 * into the database using an OutputProcessStrategy.
 */
package org.neosimulation.neo.framework.output;