/**
 * 
 */
package org.neosimulation.neo.framework.solver;

import org.neosimulation.neo.framework.model.SimulationModel;

/**
 * SolverFactory - Designed to generate Solvers for a particular SimulationModel.
 * Implementations of this interface generate the necessary solvers to both
 * intialize and execute a model in a specific way (standard loop iteration,
 * parallel iteration, cluster based distribution and iteration, etc.).
 * 
 * @author Isaac Griffith
 */
public interface SolverFactory {

    /**
     * Factory Method to create an Initialization Solver for the specified
     * model.
     * 
     * @param model
     *            Model for which an Initialization Solver is needed
     * @return A Solver of the type generated by an implementation of this
     *         interface specifically designated to initialize all statevals
     *         (with dynams) in the model.
     */
    public Solver createInitSolver(SimulationModel model);

    /**
     * Factory Method to create an Execution Solver for the specified model.
     * 
     * @param model
     *            Model for which an Execution Solver is needed
     * @return A Solver of the type generated by an implementation of this
     *         interface specifically designated to execute (update) all
     *         statevals (with dynams) in the model.
     */
    public Solver createExecSolver(SimulationModel model);
}
